version: '3.8'

services:
  frpc-web:
    build: .
    container_name: frpc-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8001}:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/frpc-web
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.example.description=FRPC Web Management Interface"
      - "com.example.service=frpc-web"
    stop_grace_period: 30s
    stop_signal: SIGTERM 
