version: '3.8'

services:
  frpc-web:
    build: .
    container_name: frpc-web
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ./logs:/var/log/frpc-web
    environment:
      - TZ=Asia/Shanghai
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - WEB_PORT=8001
      - DEFAULT_USERNAME=${DEFAULT_USERNAME:-admin}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD:-admin123}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/frpc.db}
      - NETWORK_CHECK_INTERVAL=1800
      - NETWORK_CHECK_HOSTS=8.8.8.8,114.114.114.114
      - NETWORK_CHECK_TIMEOUT=5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.example.description=FRPC Web Management Interface"
      - "com.example.service=frpc-web"
    stop_grace_period: 30s
    stop_signal: SIGTERM 